-- AlterTable
ALTER TABLE "Order" ADD COLUMN "shipName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "shipLine1" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "shipLine2" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "shipPostal" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "shipCity" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "shipCountry" TEXT NOT NULL DEFAULT 'FR';
ALTER TABLE "Order" ADD COLUMN "shipPhone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "mailedAt" TIMESTAMP(3);
